spring.application.name=lms-backend
spring.datasource.url=jdbc:mysql://localhost:3306/lms_db
spring.datasource.username=root
spring.datasource.password=Manualdelastoa123.
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

jwt.secret=a7fd66bdd556048ff7126cdd46406b31f3fa57fc169c4100da9f0860ba34728fb8e5e243f0283d1fa22e3ba537af605944dca3a03f30542efdc6261f7874a142
jwt.expiration=36000000